// Compiles and checks String Catalogs for XCodeVault (docs/process/LOCALIZATION.md).
// Usage:
//   swift scripts/l10n/l10n.swift gen   <catalog.xcstrings> <out.swift> <name> --locales en,pt-BR,...
//   swift scripts/l10n/l10n.swift check <catalog.xcstrings> <out.swift> <name> --locales ... --sources <dir>
//   swift scripts/l10n/l10n.swift add   <catalog.xcstrings> <locale>
import Foundation

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data(("l10n: " + message + "\n").utf8))
    exit(1)
}

func option(_ name: String, in args: [String]) -> String? {
    guard let i = args.firstIndex(of: name), i + 1 < args.count else { return nil }
    return args[i + 1]
}

func loadCatalog(_ path: String) -> [String: Any] {
    guard let data = FileManager.default.contents(atPath: path),
        let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
    else { fail("cannot read \(path)") }
    return json
}

/// key -> locale -> value, and key -> locale -> category -> value.
func flatten(_ catalog: [String: Any]) -> (strings: [String: [String: String]], plurals: [String: [String: [String: String]]], review: [String: Int]) {
    var strings: [String: [String: String]] = [:]
    var plurals: [String: [String: [String: String]]] = [:]
    var review: [String: Int] = [:]
    let entries = catalog["strings"] as? [String: Any] ?? [:]
    for (key, raw) in entries {
        let localizations = (raw as? [String: Any])?["localizations"] as? [String: Any] ?? [:]
        for (locale, rawLocalization) in localizations {
            let localization = rawLocalization as? [String: Any] ?? [:]
            if let unit = localization["stringUnit"] as? [String: Any] {
                strings[key, default: [:]][locale] = unit["value"] as? String ?? ""
                if unit["state"] as? String == "needs_review" { review[locale, default: 0] += 1 }
            }
            let forms = (localization["variations"] as? [String: Any])?["plural"] as? [String: Any] ?? [:]
            for (category, rawForm) in forms {
                let unit = (rawForm as? [String: Any])?["stringUnit"] as? [String: Any] ?? [:]
                plurals[key, default: [:]][locale, default: [:]][category] = unit["value"] as? String ?? ""
                if unit["state"] as? String == "needs_review" { review[locale, default: 0] += 1 }
            }
        }
    }
    return (strings, plurals, review)
}

func literal(_ s: String) -> String { String(reflecting: s) }

func generate(catalogPath: String, name: String, locales: [String]) -> String {
    let (strings, plurals, _) = flatten(loadCatalog(catalogPath))
    let order = { (a: String, b: String) in (locales.firstIndex(of: a) ?? .max, a) < (locales.firstIndex(of: b) ?? .max, b) }
    var out = "// swift-format-ignore-file\n"
    out += "// Generated by scripts/l10n.sh from \((catalogPath as NSString).lastPathComponent). Do not edit.\n\n"
    out += "extension L10nCatalog {\n    static let \(name) = L10nCatalog(\n        strings: [\n"
    for key in strings.keys.sorted() {
        out += "            \(literal(key)): [\n"
        for locale in strings[key]!.keys.sorted(by: order) { out += "                \(literal(locale)): \(literal(strings[key]![locale]!)),\n" }
        out += "            ],\n"
    }
    if strings.isEmpty { out += "            :\n" }
    out += "        ],\n        plurals: [\n"
    for key in plurals.keys.sorted() {
        out += "            \(literal(key)): [\n"
        for locale in plurals[key]!.keys.sorted(by: order) {
            out += "                \(literal(locale)): [\n"
            for category in plurals[key]![locale]!.keys.sorted() {
                out += "                    \(literal(category)): \(literal(plurals[key]![locale]![category]!)),\n"
            }
            out += "                ],\n"
        }
        out += "            ],\n"
    }
    if plurals.isEmpty { out += "            :\n" }
    out += "        ])\n}\n"
    return out
}

// The same pattern and the same "unsupported" rule as `L10n.format` at run time (Sources/XCodeVaultCore/Localization/L10n.swift).
let specifier = try! NSRegularExpression(pattern: "%(?:([0-9]+)\\$)?[-+ 0#]*[0-9]*(?:\\.[0-9]+)?(lld|llu|ld|lu|d|i|u|x|X|@|f|e|g|s|c)")

/// A template's arguments as argument number → conversion. Non-positional specifiers are numbered in order, so
/// `"%@ of %lld"` and `"%2$lld の %1$@"` compare equal and `"%lld の %@"` does not (spec §4.6: compared in order).
/// A template that mixes positional and non-positional specifiers, or that `L10n` would refuse to format, is a
/// problem rather than a signature.
func placeholders(_ s: String) -> Result<[Int: String], PlaceholderProblem> {
    let stripped = s.replacingOccurrences(of: "%%", with: "")
    if stripped.contains("%#@") { return .failure(.unsupported("%#@ (substitutions are not compiled)")) }
    let range = NSRange(stripped.startIndex..., in: stripped)
    if specifier.stringByReplacingMatches(in: stripped, range: range, withTemplate: "").contains("%") {
        return .failure(.unsupported("a % that is not a supported specifier (write %% for a literal %)"))
    }
    let matches = specifier.matches(in: stripped, range: range)
    let positions = matches.map { m in Range(m.range(at: 1), in: stripped).flatMap { Int(stripped[$0]) } }
    if positions.contains(where: { $0 == nil }) && positions.contains(where: { $0 != nil }) { return .failure(.mixed) }
    var signature: [Int: String] = [:]
    for (offset, m) in matches.enumerated() {
        let conversion = String(stripped[Range(m.range(at: 2), in: stripped)!])
        let number = positions[offset] ?? offset + 1
        if let earlier = signature[number], earlier != conversion { return .failure(.unsupported("argument \(number) used as both %\(earlier) and %\(conversion)")) }
        signature[number] = conversion
    }
    return .success(signature)
}

enum PlaceholderProblem: Error, CustomStringConvertible {
    case mixed
    case unsupported(String)
    var description: String {
        switch self {
        case .mixed: return "mixes positional (%1$@) and non-positional (%@) specifiers"
        case .unsupported(let what): return "uses \(what)"
        }
    }
}

func describe(_ signature: [Int: String]) -> String {
    "[" + signature.keys.sorted().map { "\($0):%\(signature[$0]!)" }.joined(separator: " ") + "]"
}

/// Compares `value` with the English signature; returns the problem, if any, for `where`.
func comparePlaceholders(_ value: String, base: Result<[Int: String], PlaceholderProblem>, where label: String) -> String? {
    switch (placeholders(value), base) {
    case (.failure(let problem), _): return "\(label) \(problem)"
    case (.success, .failure): return nil  // English itself is reported once, under its own label.
    case (.success(let mine), .success(let english)):
        return mine == english ? nil : "\(label) placeholders \(describe(mine)) ≠ en \(describe(english))"
    }
}

/// Catalog features the tool does not compile are refused, not ignored (spec §4.6): `substitutions`, and any
/// `variations` other than `plural` (device variations).
func shapeProblems(_ catalog: [String: Any]) -> [String] {
    var problems: [String] = []
    let entries = catalog["strings"] as? [String: Any] ?? [:]
    for key in entries.keys.sorted() {
        let localizations = (entries[key] as? [String: Any])?["localizations"] as? [String: Any] ?? [:]
        for locale in localizations.keys.sorted() {
            let localization = localizations[locale] as? [String: Any] ?? [:]
            if localization["substitutions"] != nil { problems.append("\(key): \(locale) uses substitutions, which the tool does not compile") }
            let variations = localization["variations"] as? [String: Any] ?? [:]
            for kind in variations.keys.sorted() where kind != "plural" {
                problems.append("\(key): \(locale) uses '\(kind)' variations; only 'plural' is compiled")
            }
        }
    }
    return problems
}

let keyUse = try! NSRegularExpression(pattern: "L10n\\.(?:tr|plural)\\(\\s*\"([^\"]+)\"")
func referencedKeys(under directory: String) -> [String: String] {
    var found: [String: String] = [:]
    let enumerator = FileManager.default.enumerator(atPath: directory)
    while let relative = enumerator?.nextObject() as? String {
        guard relative.hasSuffix(".swift"), !relative.hasSuffix(".generated.swift") else { continue }
        let path = directory + "/" + relative
        guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { continue }
        for m in keyUse.matches(in: text, range: NSRange(text.startIndex..., in: text)) {
            found[String(text[Range(m.range(at: 1), in: text)!])] = relative
        }
    }
    return found
}

func check(catalogPath: String, outPath: String, name: String, locales: [String], sources: String) -> Int32 {
    var problems: [String] = []
    let expected = generate(catalogPath: catalogPath, name: name, locales: locales)
    let actual = (try? String(contentsOfFile: outPath, encoding: .utf8)) ?? ""
    if actual != expected { problems.append("\(outPath) is stale: run scripts/l10n.sh gen") }
    let raw = loadCatalog(catalogPath)
    problems += shapeProblems(raw)
    let (strings, plurals, review) = flatten(raw)
    for (key, byLocale) in strings.sorted(by: { $0.key < $1.key }) {
        let base = placeholders(byLocale["en"] ?? "")
        for locale in locales {
            guard let value = byLocale[locale] else { problems.append("\(key): missing \(locale)"); continue }
            if value.isEmpty { problems.append("\(key): empty \(locale)") }
            if let problem = comparePlaceholders(value, base: base, where: "\(key): \(locale)") { problems.append(problem) }
        }
    }
    for (key, byLocale) in plurals.sorted(by: { $0.key < $1.key }) {
        let base = placeholders(byLocale["en"]?["other"] ?? "")
        for locale in locales {
            guard let forms = byLocale[locale] else { problems.append("\(key): missing plural \(locale)"); continue }
            guard forms["other"] != nil else { problems.append("\(key): \(locale) has no 'other' form"); continue }
            for (category, value) in forms.sorted(by: { $0.key < $1.key }) {
                if value.isEmpty { problems.append("\(key): empty \(locale)/\(category)") }
                if let problem = comparePlaceholders(value, base: base, where: "\(key): \(locale)/\(category)") { problems.append(problem) }
            }
        }
    }
    let known = Set(strings.keys).union(plurals.keys)
    for (key, file) in referencedKeys(under: sources).sorted(by: { $0.key < $1.key }) where !known.contains(key) {
        problems.append("\(file): key \"\(key)\" is not in \((catalogPath as NSString).lastPathComponent)")
    }
    // A catalog key no source references is a warning, not a failure: it may be used through a key built at run time.
    let referenced = Set(referencedKeys(under: sources).keys)
    for key in known.subtracting(referenced).sorted() { print("l10n: unused key \(key)") }
    for locale in locales where (review[locale] ?? 0) > 0 { print("l10n: \(locale): \(review[locale]!) string(s) need native review") }
    for p in problems { FileHandle.standardError.write(Data(("l10n: " + p + "\n").utf8)) }
    return problems.isEmpty ? 0 : 1
}

func add(catalogPath: String, locale: String) {
    var catalog = loadCatalog(catalogPath)
    var entries = catalog["strings"] as? [String: Any] ?? [:]
    func seeded(_ unit: Any?) -> Any {
        var u = unit as? [String: Any] ?? [:]
        u["state"] = "needs_review"
        return u
    }
    for (key, raw) in entries {
        var entry = raw as? [String: Any] ?? [:]
        var localizations = entry["localizations"] as? [String: Any] ?? [:]
        guard localizations[locale] == nil, let english = localizations["en"] as? [String: Any] else { continue }
        var copy = english
        if let unit = english["stringUnit"] { copy["stringUnit"] = seeded(unit) }
        if var variations = english["variations"] as? [String: Any], var plural = variations["plural"] as? [String: Any] {
            for (category, form) in plural {
                var f = form as? [String: Any] ?? [:]
                f["stringUnit"] = seeded(f["stringUnit"])
                plural[category] = f
            }
            variations["plural"] = plural
            copy["variations"] = variations
        }
        localizations[locale] = copy
        entry["localizations"] = localizations
        entries[key] = entry
    }
    catalog["strings"] = entries
    let data = try! JSONSerialization.data(withJSONObject: catalog, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
    FileManager.default.createFile(atPath: catalogPath, contents: data + Data("\n".utf8))
    print("l10n: seeded \(locale) in \(catalogPath); every string is marked needs_review")
}

let args = Array(CommandLine.arguments.dropFirst())
guard let command = args.first else { fail("usage: gen|check|add …") }
switch command {
case "gen":
    guard args.count >= 4, let locales = option("--locales", in: args) else { fail("usage: gen <catalog> <out> <name> --locales a,b") }
    let text = generate(catalogPath: args[1], name: args[3], locales: locales.split(separator: ",").map(String.init))
    FileManager.default.createFile(atPath: args[2], contents: Data(text.utf8))
case "check":
    guard args.count >= 4, let locales = option("--locales", in: args), let sources = option("--sources", in: args) else {
        fail("usage: check <catalog> <out> <name> --locales a,b --sources <dir>")
    }
    exit(check(catalogPath: args[1], outPath: args[2], name: args[3], locales: locales.split(separator: ",").map(String.init), sources: sources))
case "add":
    guard args.count == 3 else { fail("usage: add <catalog> <locale>") }
    add(catalogPath: args[1], locale: args[2])
default:
    fail("unknown command \(command)")
}
